language: node_js
sudo: false
node_js:
  - 4

cache:
   directories:
     - node_modules


after_success:
  - cat ./coverage/mocha/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose


deploy:
  provider: npm
  email: thaiat@ipelia.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    node: '4'
    repo: mcfly-io/mcfly-semantic-release
